{{- range untilStep 0 1 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-consume-{{ . }}
  namespace: confluent
spec:
  serviceName: test-consume-{{ . }}
  podManagementPolicy: Parallel
  replicas: 10
  selector:
    matchLabels:
      app: test-consume-{{ . }}
  template:
    metadata:
      labels:
        app: test-consume-{{ . }}
    spec:
      containers:
      - name: test-consume-{{ . }}
        image: confluentinc/cp-server:7.5.0
        command: ["/bin/sh"]
        args: ["-c", "kafka-console-consumer --from-beginning --bootstrap-server kafka.confluent.svc.cluster.local:9071 --topic test-topic-{{ . }} --group topics-1-test-group-10"]
        # resources:
        #   requests:
        #     memory: 10Mi # 768Mi
        #     cpu: 20m # 1000m
---
{{- end }}
