
{{- range untilStep 0 1 1 }}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: producer-example-{{ . }}
  name: producer-example-{{ . }}
  namespace: confluent  
spec:
  containers:
  - image: confluentinc/cp-server:7.5.0
    name: producer-example-{{ . }}
    command:
    - /bin/sh
    - -c
    - |
      for i in `seq 20000`; do echo '{"f1": "value'$i'"'};done  | kafka-console-producer \
            --bootstrap-server kafka.confluent.svc.cluster.local:9071 \
            --topic test-topic-{{ . }} 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
{{- end }}