{{- range untilStep 0 1 1 }}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic-{{ . }}
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 10
  configs:
    cleanup.policy: "delete"
---
 {{- end }}